sudo: false
language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
script:
  - npm install
  - npm build
  - npm run lint
  - npm run prettier-check
#   - npm run coverage
# after_success:
#   - npm run coveralls
